#!/usr/bin/env bash
# Lifecycle manager for the isolated, per-worktree Monitoring E2E test
# stack. See tests/e2e-monitoring/design.md for the full rationale (why
# isolated, why it deliberately still scrapes the real host via
# host-gateway rather than faking scrape targets too).
#
# Usage:
#   stack.sh up        Start (creating fresh test data on first run for this worktree)
#   stack.sh down       Stop the containers, keep data
#   stack.sh teardown  Stop the containers AND drop their volumes/data
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
E2E_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$E2E_DIR/../.." && pwd)"

WORKTREE_ID="$(basename "$REPO_ROOT")"
PROJECT_NAME="monitoring-e2e-test-${WORKTREE_ID}"

STATE_DIR="$E2E_DIR/.state"
ENV_FILE="$E2E_DIR/.env"

MONITORING_COMPOSE="$REPO_ROOT/modules/monitoring/compose.yaml"
OVERRIDE_COMPOSE="$E2E_DIR/fixtures/monitoring.override.yaml"

log() { echo "[monitoring-e2e-stack] $*" >&2; }
die() {
  echo "[monitoring-e2e-stack] ERROR: $*" >&2
  exit 1
}

find_free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1]); s.close()'
}

compose() {
  docker compose -p "$PROJECT_NAME" \
    -f "$MONITORING_COMPOSE" \
    -f "$OVERRIDE_COMPOSE" \
    --env-file "$ENV_FILE" \
    "$@"
}

load_env_file() {
  if [ -f "$ENV_FILE" ]; then
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
  fi
}

write_env_file() {
  cat >"$ENV_FILE" <<EOF
# Generated by tests/e2e-monitoring/scripts/stack.sh — do not commit
# (gitignored). Isolated, disposable data for this worktree's e2e stack
# only; never production. See tests/e2e-monitoring/design.md.
MONITORING_TEST_PROMETHEUS_PORT=${MONITORING_TEST_PROMETHEUS_PORT}
MONITORING_TEST_GRAFANA_PORT=${MONITORING_TEST_GRAFANA_PORT}
MONITORING_TEST_LOKI_PORT=${MONITORING_TEST_LOKI_PORT}
MONITORING_TEST_CADVISOR_PORT=${MONITORING_TEST_CADVISOR_PORT}
MONITORING_TEST_GRAFANA_VOLUME_NAME=${MONITORING_TEST_GRAFANA_VOLUME_NAME}
MONITORING_DATA_DIR=${MONITORING_DATA_DIR}
PROMETHEUS_CONFIG=${PROMETHEUS_CONFIG}
PROMETHEUS_RULES=${PROMETHEUS_RULES}
LOKI_CONFIG=${LOKI_CONFIG}
ALLOY_CONFIG=${ALLOY_CONFIG}
GRAFANA_PROVISIONING_DIR=${GRAFANA_PROVISIONING_DIR}
GRAFANA_DASHBOARDS_DIR=${GRAFANA_DASHBOARDS_DIR}
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
GRAFANA_ROOT_URL=${GRAFANA_ROOT_URL}
GRAFANA_OIDC_CLIENT_ID=unused-in-e2e-stack
GRAFANA_OIDC_CLIENT_SECRET=unused-in-e2e-stack
GRAFANA_OIDC_ISSUER=http://unused-in-e2e-stack.invalid
PROMETHEUS_URL=http://127.0.0.1:${MONITORING_TEST_PROMETHEUS_PORT}
GRAFANA_URL=${GRAFANA_ROOT_URL}
LOKI_URL=http://127.0.0.1:${MONITORING_TEST_LOKI_PORT}
EOF
}

derive_env() {
  load_env_file
  : "${MONITORING_TEST_PROMETHEUS_PORT:=$(find_free_port)}"
  : "${MONITORING_TEST_GRAFANA_PORT:=$(find_free_port)}"
  : "${MONITORING_TEST_LOKI_PORT:=$(find_free_port)}"
  : "${MONITORING_TEST_CADVISOR_PORT:=$(find_free_port)}"
  MONITORING_TEST_GRAFANA_VOLUME_NAME="${PROJECT_NAME}-grafana-data"
  MONITORING_DATA_DIR="$STATE_DIR/data"
  # Same repo config files production uses (modules/monitoring/options.nix's
  # prometheusConfig/etc.) - the whole point is verifying the real
  # scrape config against real targets, not a test-only substitute.
  PROMETHEUS_CONFIG="$REPO_ROOT/modules/monitoring/prometheus.yml"
  PROMETHEUS_RULES="$REPO_ROOT/modules/monitoring/prometheus-rules.yml"
  LOKI_CONFIG="$REPO_ROOT/modules/monitoring/loki-config.yml"
  ALLOY_CONFIG="$REPO_ROOT/modules/monitoring/alloy-config.alloy"
  GRAFANA_PROVISIONING_DIR="$REPO_ROOT/modules/monitoring/grafana/provisioning"
  GRAFANA_DASHBOARDS_DIR="$REPO_ROOT/modules/monitoring/grafana/dashboards"
  GRAFANA_ADMIN_PASSWORD="unused-in-e2e-stack"
  GRAFANA_ROOT_URL="http://127.0.0.1:${MONITORING_TEST_GRAFANA_PORT}"
  export MONITORING_TEST_PROMETHEUS_PORT MONITORING_TEST_GRAFANA_PORT
  export MONITORING_TEST_LOKI_PORT MONITORING_TEST_CADVISOR_PORT
  export MONITORING_TEST_GRAFANA_VOLUME_NAME MONITORING_DATA_DIR
  export PROMETHEUS_CONFIG PROMETHEUS_RULES LOKI_CONFIG ALLOY_CONFIG
  export GRAFANA_PROVISIONING_DIR GRAFANA_DASHBOARDS_DIR
  export GRAFANA_ADMIN_PASSWORD GRAFANA_ROOT_URL
  write_env_file
  # Matches options.nix's own launchd pre-start (mkdir + world-writable):
  # prometheus/loki both run as non-root in-container users writing to
  # these bind mounts.
  mkdir -p "$MONITORING_DATA_DIR/prometheus" "$MONITORING_DATA_DIR/loki"
  chmod -R 777 "$MONITORING_DATA_DIR"
}

wait_healthy() {
  log "waiting for prometheus at http://127.0.0.1:${MONITORING_TEST_PROMETHEUS_PORT} ..."
  for _ in $(seq 1 60); do
    if curl -sf "http://127.0.0.1:${MONITORING_TEST_PROMETHEUS_PORT}/-/healthy" -o /dev/null 2>/dev/null; then
      log "prometheus is up"
      break
    fi
    sleep 2
  done
  log "waiting for grafana at ${GRAFANA_ROOT_URL} ..."
  for _ in $(seq 1 60); do
    if curl -sf "${GRAFANA_ROOT_URL}/api/health" -o /dev/null 2>/dev/null; then
      log "grafana is up"
      return 0
    fi
    sleep 2
  done
  die "grafana did not become healthy at ${GRAFANA_ROOT_URL} in time"
}

cmd_up() {
  derive_env
  compose up -d
  wait_healthy
  log "prometheus: http://127.0.0.1:${MONITORING_TEST_PROMETHEUS_PORT}  grafana: ${GRAFANA_ROOT_URL}  loki: http://127.0.0.1:${MONITORING_TEST_LOKI_PORT}"
}

cmd_down() {
  derive_env
  compose stop
}

cmd_teardown() {
  derive_env
  compose down -v --remove-orphans 2>/dev/null || true
  rm -rf "$MONITORING_DATA_DIR"
}

case "${1:-}" in
up) cmd_up ;;
down) cmd_down ;;
teardown) cmd_teardown ;;
*)
  die "usage: $0 {up|down|teardown}"
  ;;
esac
