{ ... }:
{
  imports = [
    ./altserver/darwin.nix
    ./attic/darwin.nix
    ./dotfiles/darwin.nix
    ./brew-nix/darwin.nix
    ./caddy/darwin.nix
    ./desktoppr/darwin.nix
    ./dnsmasq/darwin.nix
    ./docker/darwin.nix
    ./forgejo/darwin.nix
    ./ghostty/darwin.nix
    ./gitlab/darwin.nix
    ./immich/darwin.nix
    ./llm-server/darwin.nix
    ./mlx-server/darwin.nix
    ./opencode-web/darwin.nix
    ./pi-web/darwin.nix
    ./lm-studio/darwin.nix
    ./monitoring/darwin.nix
    ./mtplx/darwin.nix
    ./navidrome/darwin.nix
    ./navidrome/darwin.nix
    ./nix/darwin.nix
    ./opencloud/darwin.nix
    ./pocket-id/darwin.nix
    ./ssh/darwin.nix
    ./static-reports/darwin.nix
    ./storage/darwin.nix
    ./stylix/darwin.nix
    ./tailscale/darwin.nix
    ./tart/darwin.nix
    ./zsh/darwin.nix
  ];
}
