{
  imports = [
    ./agent-search/home.nix
    ./ai-rules/home.nix
    ./attic/home.nix
    ./build-tools/home.nix
    ./caddy/home.nix
    ./claude/home.nix
    ./cli-tools/home.nix
    ./cloud-tools/home.nix
    ./cursor/home.nix
    ./obsidian/home.nix
    ./databases/home.nix
    ./difit/home.nix
    ./dotfiles/home.nix
    ./direnv/home.nix
    ./docker/home.nix
    ./emacs/home.nix
    ./fresh/home.nix
    ./forgejo/home.nix
    ./fzf/home.nix
    ./git/home.nix
    ./gitui/home.nix
    ./grafana/home.nix
    ./gmake/home.nix
    ./go-task/home.nix
    ./gpg/home.nix
    ./graphics-tools/home.nix
    ./haskell/home.nix
    ./herdr/home.nix
    ./hunk/home.nix
    ./immich/home.nix
    ./just/home.nix
    ./languages/home.nix
    ./lazygit/home.nix
    ./nix/home.nix
    ./nix-formatter/home.nix
    ./nodejs/home.nix
    ./openclaw/home.nix
    ./opencloud/home.nix
    ./opencode/home.nix
    ./php/home.nix
    ./pinentry/home.nix
    ./pocket-id/home.nix
    ./python/home.nix
    ./rust/home.nix
    ./serena/home.nix
    ./sops/home.nix
    ./ssh/home.nix
    ./sync-home-files/home.nix
    ./tmux/home.nix
    ./vscode/home.nix
    ./workmux/home.nix
    ./worktrunk/home.nix
    ./yazi/home.nix
    ./zsh/home.nix
  ];
}
