{
  imports = [
    ./attic/home.nix
    ./cursor/home.nix
    ./direnv/home.nix
    ./docker/home.nix
    ./emacs/home.nix
    ./fzf/home.nix
    ./ghostty/home.nix
    ./git/home.nix
    ./gitui/home.nix
    ./gmake/home.nix
    ./go-task/home.nix
    ./haskell/home.nix
    ./just/home.nix
    ./nix-formatter/home.nix
    ./nodejs/home.nix
    ./php/home.nix
    ./python/home.nix
    ./sops/home.nix
    ./ssh/home.nix
    ./tmux/home.nix
    ./zsh/home.nix
    ./pinentry/home.nix
    ./sync-home-files/home.nix
    ./vscode/home.nix
    ./yazi/home.nix
  ];
}
