#!/usr/bin/env bash
# Lifecycle manager for the isolated, per-worktree pocket-id + OpenCloud
# E2E test stack. See tests/e2e/design.md for the full rationale (why
# per-worktree, why a Caddy front door for both services, why disposable
# identity).
#
# Usage:
#   stack.sh up        Start (bootstrapping on first run for this worktree)
#   stack.sh down       Stop containers + test Caddy, keep data
#   stack.sh teardown  Stop everything AND drop the docker network/volumes
#                        (data itself lives under tests/e2e/.state, which is
#                        removed by deleting the worktree, not by this)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
E2E_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$E2E_DIR/../.." && pwd)"

WORKTREE_ID="$(basename "$REPO_ROOT")"
PROJECT_NAME="opencloud-e2e-test-${WORKTREE_ID}"

STATE_DIR="$E2E_DIR/.state"
ENV_FILE="$E2E_DIR/.env"
PLAYWRIGHT_ENV_FILE="$STATE_DIR/env-for-playwright.sh"

POCKET_ID_COMPOSE="$REPO_ROOT/modules/pocket-id/compose.yaml"
POCKET_ID_OVERRIDE_COMPOSE="$E2E_DIR/fixtures/pocket-id.override.yaml"
OPENCLOUD_COMPOSE="$REPO_ROOT/modules/opencloud/compose.yaml"
OPENCLOUD_OVERRIDE_COMPOSE="$E2E_DIR/fixtures/opencloud.override.yaml"
CSP_TEMPLATE="$E2E_DIR/fixtures/csp.yaml.template"

CADDY_DATA_DIR="$STATE_DIR/test-caddy-data"
CADDY_PID_FILE="$STATE_DIR/test-caddy.pid"
CADDYFILE="$STATE_DIR/test-Caddyfile"
CADDY_LOG_FILE="$STATE_DIR/test-caddy.log"
PROD_CA_DIR="/var/lib/caddy/caddy/pki/authorities/local"
TEST_CA_DIR="$CADDY_DATA_DIR/caddy/pki/authorities/local"

log() { echo "[e2e-stack] $*" >&2; }
die() { echo "[e2e-stack] ERROR: $*" >&2; exit 1; }

find_free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1]); s.close()'
}

port_is_free() {
  python3 -c "
import socket, sys
s = socket.socket()
try:
    s.bind(('127.0.0.1', $1))
    s.close()
    sys.exit(0)
except OSError:
    sys.exit(1)
"
}

compose() {
  docker compose -p "$PROJECT_NAME" \
    -f "$POCKET_ID_COMPOSE" \
    -f "$POCKET_ID_OVERRIDE_COMPOSE" \
    -f "$OPENCLOUD_COMPOSE" \
    -f "$OPENCLOUD_OVERRIDE_COMPOSE" \
    --env-file "$ENV_FILE" \
    "$@"
}

# Loads existing persisted config (secrets, ports, bootstrap results) from
# a prior run of this worktree, if any, into the current shell's env.
load_env_file() {
  if [ -f "$ENV_FILE" ]; then
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
  fi
}

# (Re)writes .env from the current shell's env vars. Called after every
# generation/bootstrap step so partial progress survives a re-run.
write_env_file() {
  cat > "$ENV_FILE" <<EOF
# Generated by tests/e2e/scripts/stack.sh — do not commit (gitignored).
# Isolated, disposable secrets for this worktree's e2e stack only; never
# production credentials. See tests/e2e/design.md.
POCKET_ID_HOST_PORT=${POCKET_ID_HOST_PORT}
OPENCLOUD_HOST_PORT=${OPENCLOUD_HOST_PORT}
OPENCLOUD_DEBUG_HOST_PORT=${OPENCLOUD_DEBUG_HOST_PORT}
CADDY_POCKET_ID_PORT=${CADDY_POCKET_ID_PORT}
CADDY_OPENCLOUD_PORT=${CADDY_OPENCLOUD_PORT}
OPENCLOUD_ADMIN_PASSWORD=${OPENCLOUD_ADMIN_PASSWORD}
POCKET_ID_API_KEY=${POCKET_ID_API_KEY:-}
OPENCLOUD_GROUP_ID=${OPENCLOUD_GROUP_ID:-}
OPENCLOUD_OIDC_CLIENT_ID=${OPENCLOUD_OIDC_CLIENT_ID:-}
EOF
}

derive_env() {
  load_env_file
  : "${POCKET_ID_HOST_PORT:=$(find_free_port)}"
  : "${OPENCLOUD_HOST_PORT:=$(find_free_port)}"
  : "${OPENCLOUD_DEBUG_HOST_PORT:=$(find_free_port)}"
  : "${CADDY_POCKET_ID_PORT:=$(find_free_port)}"
  : "${CADDY_OPENCLOUD_PORT:=$(find_free_port)}"
  : "${OPENCLOUD_ADMIN_PASSWORD:=$(openssl rand -base64 24)}"
  write_env_file

  mkdir -p "$STATE_DIR/pocket-id/data" \
    "$STATE_DIR/opencloud/data" \
    "$STATE_DIR/opencloud/config" \
    "$STATE_DIR/opencloud/user-files" \
    "$STATE_DIR/opencloud/apps"

  ENCRYPTION_KEY_FILE="$STATE_DIR/pocket-id/encryption_key"
  if [ ! -f "$ENCRYPTION_KEY_FILE" ]; then
    openssl rand -base64 32 > "$ENCRYPTION_KEY_FILE"
    chmod 600 "$ENCRYPTION_KEY_FILE"
  fi

  local tailscale_ip hostname_short domain
  tailscale_ip="$(tailscale ip -4)"
  hostname_short="$(scutil --get LocalHostName 2>/dev/null || hostname -s)"
  domain="${hostname_short}.internal"
  POCKET_ID_VHOST="${WORKTREE_ID}-pocket-id-test.${domain}"
  OPENCLOUD_VHOST="${WORKTREE_ID}-opencloud-test.${domain}"

  export POCKET_ID_APP_URL="https://${POCKET_ID_VHOST}:${CADDY_POCKET_ID_PORT}"
  export POCKET_ID_DATA_DIR="$STATE_DIR/pocket-id/data"
  export POCKET_ID_ENCRYPTION_KEY_FILE="$ENCRYPTION_KEY_FILE"
  export POCKET_ID_VOLUME_NAME="${PROJECT_NAME}-pocket-id-data"

  export OPENCLOUD_DATA_DIR="$STATE_DIR/opencloud/data"
  export OPENCLOUD_CONFIG_DIR="$STATE_DIR/opencloud/config"
  export OPENCLOUD_USER_FILES_DIR="$STATE_DIR/opencloud/user-files"
  export OPENCLOUD_APPS_DIR="$STATE_DIR/opencloud/apps"
  export OPENCLOUD_URL="https://${OPENCLOUD_VHOST}:${CADDY_OPENCLOUD_PORT}"
  export OPENCLOUD_HOST_DOMAIN="$OPENCLOUD_VHOST"
  export OPENCLOUD_OIDC_ISSUER="$POCKET_ID_APP_URL"
  export OPENCLOUD_OIDC_DOMAIN="$POCKET_ID_VHOST"
  export OPENCLOUD_OIDC_ROLE_CLAIM="opencloud_role"
  export OPENCLOUD_OIDC_CLIENT_ID="${OPENCLOUD_OIDC_CLIENT_ID:-}"
  export OPENCLOUD_OIDC_PROXY_CLIENT_ID="${OPENCLOUD_OIDC_CLIENT_ID:-}"

  CSP_FILE="$STATE_DIR/opencloud/csp.yaml"
  sed \
    -e "s#__POCKET_ID_HTTP_ORIGIN__#${POCKET_ID_APP_URL}#g" \
    -e "s#__POCKET_ID_WS_ORIGIN__#wss://${POCKET_ID_VHOST}:${CADDY_POCKET_ID_PORT}#g" \
    "$CSP_TEMPLATE" > "$CSP_FILE"
  export OPENCLOUD_CSP_FILE="$CSP_FILE"

  TAILSCALE_IP="$tailscale_ip"
  DOMAIN="$domain"
}

# Only meaningful right before actually starting containers (cmd_up) —
# calling this from cmd_down/cmd_teardown right after our own containers
# just stopped can catch their host ports in a brief not-yet-released
# state and misreport them as taken by something else.
check_ports_available() {
  for p in "$POCKET_ID_HOST_PORT" "$OPENCLOUD_HOST_PORT" "$CADDY_POCKET_ID_PORT" "$CADDY_OPENCLOUD_PORT"; do
    if ! port_is_free "$p" && [ -z "$(compose ps -a -q 2>/dev/null)" ] && [ ! -f "$CADDY_PID_FILE" ]; then
      die "port $p (persisted for this worktree) is in use by something else. Free it, or delete $ENV_FILE to re-pick ports (this invalidates the registered OIDC client — bootstrap will need to redo the client-creation step)."
    fi
  done
}

# Copies (not live-shares) production Caddy's internal CA root cert+key so
# the test Caddy's tls-internal-issued leaf certs chain to a root already
# trusted by every client that already trusts production's CA. Needs sudo
# once per worktree (root-owned source directory).
ensure_test_ca() {
  mkdir -p "$TEST_CA_DIR"
  if [ ! -f "$TEST_CA_DIR/root.crt" ]; then
    log "copying production's internal CA identity (needs sudo to read /var/lib/caddy)..."
    sudo cp "$PROD_CA_DIR/root.crt" "$PROD_CA_DIR/root.key" "$TEST_CA_DIR/"
    sudo chown "$(id -u):$(id -g)" "$TEST_CA_DIR/root.crt" "$TEST_CA_DIR/root.key"
  fi
}

# Starts the per-worktree Caddy front door for both services, bound to
# both loopback (for local Playwright runs) and the Tailscale IP (so the
# same origin is reachable from other tailnet devices for manual
# verification or to redo the bootstrap ceremony away from a screen-share
# session) — see tests/e2e/design.md on why this replaced a
# localhost-only design (pocket-id's WebAuthn RPOrigins is fixed to
# POCKET_ID_APP_URL at startup and must match the browser's origin
# exactly, so "local" and "remote" access must be the *same* origin, not
# two different ones).
start_caddy() {
  # Idempotency safety: calling `up` twice without a `down`/`teardown` in
  # between (easy to do, since it's harmless for the docker containers
  # themselves) previously leaked an orphaned caddy process every time,
  # since nothing stopped whatever was already running before starting a
  # new one.
  stop_caddy
  ensure_test_ca

  cat > "$CADDYFILE" <<EOF
{
  admin off
  # Only the explicit HTTPS ports below are needed; without this, Caddy's
  # auto_https also tries to bind :80 for HTTP->HTTPS redirects, which
  # fails with permission denied for a non-root process.
  auto_https disable_redirects
}

https://${POCKET_ID_VHOST}:${CADDY_POCKET_ID_PORT} {
  bind ${TAILSCALE_IP} 127.0.0.1
  tls internal
  reverse_proxy 127.0.0.1:${POCKET_ID_HOST_PORT}
}

https://${OPENCLOUD_VHOST}:${CADDY_OPENCLOUD_PORT} {
  bind ${TAILSCALE_IP} 127.0.0.1
  tls internal
  reverse_proxy 127.0.0.1:${OPENCLOUD_HOST_PORT} {
    flush_interval -1
  }
}
EOF

  (
    export CADDY_DATA_DIR XDG_DATA_HOME HOME
    XDG_DATA_HOME="$CADDY_DATA_DIR"
    HOME="$CADDY_DATA_DIR"
    exec nohup caddy run --config "$CADDYFILE" --adapter caddyfile > "$CADDY_LOG_FILE" 2>&1
  ) &
  echo $! > "$CADDY_PID_FILE"

  sleep 1
  if ! kill -0 "$(cat "$CADDY_PID_FILE")" 2>/dev/null; then
    die "test Caddy failed to start — see $CADDY_LOG_FILE"
  fi
  log "pocket-id reachable at: ${POCKET_ID_APP_URL}"
  log "opencloud reachable at: ${OPENCLOUD_URL}"
  log "(both also reachable from other tailnet devices at the same URLs;"
  log " resolves via the existing wildcard *.${DOMAIN} -> Tailscale IP dnsmasq entry)"
}

stop_caddy() {
  if [ -f "$CADDY_PID_FILE" ]; then
    kill "$(cat "$CADDY_PID_FILE")" 2>/dev/null || true
    rm -f "$CADDY_PID_FILE"
  fi
}

wait_healthy() {
  local name="$1" url="$2"
  log "waiting for $name at $url ..."
  for _ in $(seq 1 60); do
    if curl -skf "$url" -o /dev/null 2>/dev/null; then
      log "$name is up"
      return 0
    fi
    sleep 2
  done
  die "$name did not become healthy at $url in time"
}

pocket_id_api() {
  local method="$1" path="$2" body="${3:-}"
  local args=(-sfk -X "$method" "${POCKET_ID_APP_URL}${path}" \
    -H "X-API-KEY: $POCKET_ID_API_KEY" -H "Content-Type: application/json")
  if [ -n "$body" ]; then args+=(-d "$body"); fi
  curl "${args[@]}"
}

bootstrap_if_needed() {
  if [ -n "${POCKET_ID_API_KEY:-}" ] && [ -n "${OPENCLOUD_GROUP_ID:-}" ] && [ -n "${OPENCLOUD_OIDC_CLIENT_ID:-}" ]; then
    log "already bootstrapped for this worktree, skipping manual setup"
    return 0
  fi

  echo "" >&2
  echo "=== One-time Pocket ID bootstrap for worktree '$WORKTREE_ID' ===" >&2
  echo "1. Open in a browser (locally, or from any other tailnet device):" >&2
  echo "   ${POCKET_ID_APP_URL}/setup" >&2
  echo "   Create the admin account and register a passkey (real Touch ID" >&2
  echo "   / security key required — this cannot be automated)." >&2
  echo "2. Go to Settings -> Admin -> API Keys, create a key, copy it." >&2
  echo -n "Paste the API key here: " >&2
  read -r POCKET_ID_API_KEY
  [ -n "$POCKET_ID_API_KEY" ] || die "no API key entered"
  export POCKET_ID_API_KEY
  write_env_file

  if [ -z "${OPENCLOUD_GROUP_ID:-}" ]; then
    log "creating opencloud_users group..."
    OPENCLOUD_GROUP_ID=$(pocket_id_api POST /api/user-groups \
      '{"name":"opencloud_users","friendlyName":"OpenCloud Users"}' | jq -r '.id')
    pocket_id_api PUT "/api/custom-claims/user-group/${OPENCLOUD_GROUP_ID}" \
      '[{"key":"opencloud_role","value":"opencloudUser"}]' >/dev/null
    export OPENCLOUD_GROUP_ID
    write_env_file
  fi

  if [ -z "${OPENCLOUD_OIDC_CLIENT_ID:-}" ]; then
    log "creating OpenCloud OIDC client..."
    local callback_urls
    callback_urls=$(jq -n --arg base "$OPENCLOUD_URL" \
      '[$base + "/", $base + "/oidc-callback.html", $base + "/oidc-silent-redirect.html"]')
    OPENCLOUD_OIDC_CLIENT_ID=$(pocket_id_api POST /api/oidc/clients \
      "$(jq -n --argjson cb "$callback_urls" --arg base "$OPENCLOUD_URL" '{
        id: "opencloud-web",
        name: "OpenCloud (e2e)",
        isPublic: true,
        pkceEnabled: true,
        isGroupRestricted: true,
        callbackURLs: $cb,
        logoutCallbackURLs: [$base + "/"]
      }')" | jq -r '.id')
    pocket_id_api PUT "/api/oidc/clients/${OPENCLOUD_OIDC_CLIENT_ID}/allowed-user-groups" \
      "$(jq -n --arg gid "$OPENCLOUD_GROUP_ID" '{userGroupIds: [$gid]}')" >/dev/null
    export OPENCLOUD_OIDC_CLIENT_ID
    export OPENCLOUD_OIDC_PROXY_CLIENT_ID="$OPENCLOUD_OIDC_CLIENT_ID"
    write_env_file
  fi

  log "bootstrap complete for worktree '$WORKTREE_ID'"
}

cmd_up() {
  derive_env
  check_ports_available
  compose up -d
  start_caddy
  wait_healthy "pocket-id" "${POCKET_ID_APP_URL}/healthz"
  wait_healthy "opencloud" "${OPENCLOUD_URL}/health"
  bootstrap_if_needed

  # bootstrap_if_needed may have just created OPENCLOUD_OIDC_CLIENT_ID —
  # opencloud was started before that with it blank, so its env needs to
  # be re-applied. `compose up -d` recreates only the services whose
  # resolved config actually changed, so this is a cheap no-op on every
  # run after the first for a given worktree.
  compose up -d
  wait_healthy "opencloud" "${OPENCLOUD_URL}/health"

  mkdir -p "$STATE_DIR"
  cat > "$PLAYWRIGHT_ENV_FILE" <<EOF
export POCKET_ID_URL="${POCKET_ID_APP_URL}"
export POCKET_ID_API_KEY="${POCKET_ID_API_KEY}"
export OPENCLOUD_URL="${OPENCLOUD_URL}"
export OPENCLOUD_GROUP_ID="${OPENCLOUD_GROUP_ID}"
export OPENCLOUD_USER_FILES_DIR="${OPENCLOUD_USER_FILES_DIR}"
EOF
  log "stack up. env for playwright written to $PLAYWRIGHT_ENV_FILE"
}

cmd_down() {
  # compose() needs the same derived vars (POCKET_ID_APP_URL, etc.) that
  # derive_env sets to correctly interpolate the compose files — without
  # them docker compose can't even identify the services to stop.
  derive_env
  stop_caddy
  compose stop
}

cmd_teardown() {
  derive_env
  stop_caddy
  compose down -v --remove-orphans 2>/dev/null || true
}

case "${1:-}" in
  up) cmd_up ;;
  down) cmd_down ;;
  teardown) cmd_teardown ;;
  *)
    die "usage: $0 {up|down|teardown}"
    ;;
esac
