#!/usr/bin/env bash
# Lifecycle manager for the isolated, per-worktree Immich E2E test stack.
# See tests/e2e-immich/design.md for the full rationale (why isolated,
# why it never touches the real modules/immich instance or its data).
#
# Usage:
#   stack.sh up        Start (creating fresh test data on first run for this worktree)
#   stack.sh down       Stop the containers, keep data
#   stack.sh teardown  Stop the containers AND drop their volumes/data
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
E2E_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$E2E_DIR/../.." && pwd)"

WORKTREE_ID="$(basename "$REPO_ROOT")"
PROJECT_NAME="immich-e2e-test-${WORKTREE_ID}"

STATE_DIR="$E2E_DIR/.state"
ENV_FILE="$E2E_DIR/.env"

IMMICH_COMPOSE="$REPO_ROOT/modules/immich/compose.yaml"
OVERRIDE_COMPOSE="$E2E_DIR/fixtures/immich.override.yaml"

log() { echo "[immich-e2e-stack] $*" >&2; }
die() { echo "[immich-e2e-stack] ERROR: $*" >&2; exit 1; }

find_free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1]); s.close()'
}

compose() {
  docker compose -p "$PROJECT_NAME" \
    -f "$IMMICH_COMPOSE" \
    -f "$OVERRIDE_COMPOSE" \
    --env-file "$ENV_FILE" \
    "$@"
}

load_env_file() {
  if [ -f "$ENV_FILE" ]; then
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
  fi
}

write_env_file() {
  cat > "$ENV_FILE" <<EOF
# Generated by tests/e2e-immich/scripts/stack.sh — do not commit (gitignored).
# Isolated, disposable data for this worktree's e2e stack only; never
# production. See tests/e2e-immich/design.md.
IMMICH_TEST_WEB_PORT=${IMMICH_TEST_WEB_PORT}
IMMICH_TEST_API_METRICS_PORT=${IMMICH_TEST_API_METRICS_PORT}
IMMICH_TEST_ML_METRICS_PORT=${IMMICH_TEST_ML_METRICS_PORT}
IMMICH_TEST_PG_EXPORTER_PORT=${IMMICH_TEST_PG_EXPORTER_PORT}
IMMICH_TEST_REDIS_EXPORTER_PORT=${IMMICH_TEST_REDIS_EXPORTER_PORT}
IMMICH_DB_PASSWORD=${IMMICH_DB_PASSWORD}
IMMICH_DB_DIR=${IMMICH_DB_DIR}
IMMICH_UPLOAD_DIR=${IMMICH_UPLOAD_DIR}
IMMICH_SERVER_URL=${IMMICH_SERVER_URL}
IMMICH_HOST_DOMAIN=${IMMICH_HOST_DOMAIN}
IMMICH_OIDC_ISSUER=unused-in-e2e-stack
IMMICH_OIDC_CLIENT_ID=unused-in-e2e-stack
IMMICH_OIDC_CLIENT_SECRET=unused-in-e2e-stack
EOF
}

derive_env() {
  load_env_file
  : "${IMMICH_TEST_WEB_PORT:=$(find_free_port)}"
  : "${IMMICH_TEST_API_METRICS_PORT:=$(find_free_port)}"
  : "${IMMICH_TEST_ML_METRICS_PORT:=$(find_free_port)}"
  : "${IMMICH_TEST_PG_EXPORTER_PORT:=$(find_free_port)}"
  : "${IMMICH_TEST_REDIS_EXPORTER_PORT:=$(find_free_port)}"
  IMMICH_DB_PASSWORD="unused-in-e2e-stack"
  IMMICH_DB_DIR="$STATE_DIR/db"
  IMMICH_UPLOAD_DIR="$STATE_DIR/upload"
  IMMICH_SERVER_URL="http://127.0.0.1:${IMMICH_TEST_WEB_PORT}"
  # extra_hosts needs a syntactically valid hostname even though nothing
  # in this isolated stack ever resolves or dials it (no OIDC exercised).
  IMMICH_HOST_DOMAIN="unused-immich-e2e.internal"
  export IMMICH_TEST_WEB_PORT IMMICH_TEST_API_METRICS_PORT IMMICH_TEST_ML_METRICS_PORT
  export IMMICH_TEST_PG_EXPORTER_PORT IMMICH_TEST_REDIS_EXPORTER_PORT
  export IMMICH_DB_PASSWORD IMMICH_DB_DIR IMMICH_UPLOAD_DIR IMMICH_SERVER_URL IMMICH_HOST_DOMAIN
  write_env_file
  mkdir -p "$IMMICH_DB_DIR" "$IMMICH_UPLOAD_DIR"
}

wait_healthy() {
  log "waiting for immich at ${IMMICH_SERVER_URL} ..."
  for _ in $(seq 1 90); do
    if curl -sf "${IMMICH_SERVER_URL}/api/server/ping" -o /dev/null 2>/dev/null; then
      log "immich is up"
      return 0
    fi
    sleep 2
  done
  die "immich did not become healthy at ${IMMICH_SERVER_URL} in time"
}

cmd_up() {
  derive_env
  compose up -d
  wait_healthy
  log "web: ${IMMICH_SERVER_URL}  upload dir: ${IMMICH_UPLOAD_DIR}"
}

cmd_down() {
  derive_env
  compose stop
}

cmd_teardown() {
  derive_env
  compose down -v --remove-orphans 2>/dev/null || true
  rm -rf "$IMMICH_DB_DIR" "$IMMICH_UPLOAD_DIR"
}

case "${1:-}" in
  up) cmd_up ;;
  down) cmd_down ;;
  teardown) cmd_teardown ;;
  *)
    die "usage: $0 {up|down|teardown}"
    ;;
esac
