#!/usr/bin/env bash
# Lifecycle manager for the isolated, per-worktree Pocket ID + static-reports
# forward_auth E2E test stack. See tests/e2e-reports/design.md for the full
# rationale (why per-worktree, why a Caddy front door, why oauth2-proxy).
#
# Stack layout (mirrors production modules/static-reports):
#   pocket-id container (docker)  <- test Caddy <- browser
#   oauth2-proxy (native, loopback only) <- test Caddy (forward_auth)
#   static reports dir (STATE_DIR/reports) <- test Caddy (file_server browse)
#
# Usage:
#   stack.sh up        Start (bootstrapping on first run for this worktree)
#   stack.sh down       Stop containers + test Caddy + oauth2-proxy, keep data
#   stack.sh teardown  Stop everything AND drop the docker network/volumes
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
E2E_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$E2E_DIR/../.." && pwd)"

WORKTREE_ID="$(basename "$REPO_ROOT")"
PROJECT_NAME="reports-e2e-test-${WORKTREE_ID}"

STATE_DIR="$E2E_DIR/.state"
ENV_FILE="$E2E_DIR/.env"

POCKET_ID_COMPOSE="$REPO_ROOT/modules/pocket-id/compose.yaml"
POCKET_ID_OVERRIDE_COMPOSE="$E2E_DIR/fixtures/pocket-id.override.yaml"

CADDY_DATA_DIR="$STATE_DIR/test-caddy-data"
CADDY_PID_FILE="$STATE_DIR/test-caddy.pid"
CADDYFILE="$STATE_DIR/test-Caddyfile"
CADDY_LOG_FILE="$STATE_DIR/test-caddy.log"
OAUTH2_PROXY_PID_FILE="$STATE_DIR/oauth2-proxy.pid"
OAUTH2_PROXY_LOG_FILE="$STATE_DIR/oauth2-proxy.log"
PROD_CA_DIR="/var/lib/caddy/caddy/pki/authorities/local"
TEST_CA_DIR="$CADDY_DATA_DIR/caddy/pki/authorities/local"

# Files the gate protects; the spec asserts this one is visible and readable
# after login.
HELLO_FILE="$STATE_DIR/reports/e2e-hello.txt"

log() { echo "[reports-e2e-stack] $*" >&2; }
die() { echo "[reports-e2e-stack] ERROR: $*" >&2; exit 1; }

find_free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1]); s.close()'
}

port_is_free() {
  python3 -c "
import socket, sys
s = socket.socket()
try:
    s.bind(('127.0.0.1', $1))
    s.close()
    sys.exit(0)
except OSError:
    sys.exit(1)
"
}

compose() {
  docker compose -p "$PROJECT_NAME" \
    -f "$POCKET_ID_COMPOSE" \
    -f "$POCKET_ID_OVERRIDE_COMPOSE" \
    --env-file "$ENV_FILE" \
    "$@"
}

load_env_file() {
  if [ -f "$ENV_FILE" ]; then
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
  fi
}

write_env_file() {
  cat > "$ENV_FILE" <<EOF
# Generated by tests/e2e-reports/scripts/stack.sh — do not commit
# (gitignored). Isolated, disposable secrets for this worktree's e2e stack
# only; never production credentials. See tests/e2e-reports/design.md.
POCKET_ID_HOST_PORT=${POCKET_ID_HOST_PORT}
CADDY_POCKET_ID_PORT=${CADDY_POCKET_ID_PORT}
CADDY_REPORTS_PORT=${CADDY_REPORTS_PORT}
OAUTH2_PROXY_PORT=${OAUTH2_PROXY_PORT}
REPORTS_COOKIE_SECRET=${REPORTS_COOKIE_SECRET}
POCKET_ID_API_KEY=${POCKET_ID_API_KEY:-}
REPORTS_GROUP_ID=${REPORTS_GROUP_ID:-}
REPORTS_OIDC_CLIENT_ID=${REPORTS_OIDC_CLIENT_ID:-}
REPORTS_OIDC_CLIENT_SECRET=${REPORTS_OIDC_CLIENT_SECRET:-}
POCKET_ID_URL=${POCKET_ID_APP_URL}
REPORTS_URL=${REPORTS_URL}
EOF
}

derive_env() {
  load_env_file
  : "${POCKET_ID_HOST_PORT:=$(find_free_port)}"
  : "${CADDY_POCKET_ID_PORT:=$(find_free_port)}"
  : "${CADDY_REPORTS_PORT:=$(find_free_port)}"
  : "${OAUTH2_PROXY_PORT:=$(find_free_port)}"
  # oauth2-proxy's --cookie-secret only auto-decodes URL-safe base64
  # (`-`/`_`) into raw AES key bytes; standard base64's `+`/`/` chars make
  # it fall back to treating the 44-char string itself as the key, which
  # fails its 16/24/32-byte check. `tr` converts the alphabet without
  # changing byte length. Verified against oauth2-proxy v7.15.2.
  : "${REPORTS_COOKIE_SECRET:=$(openssl rand -base64 32 | tr '+/' '-_')}"

  mkdir -p "$STATE_DIR/pocket-id/data" "$STATE_DIR/reports"

  ENCRYPTION_KEY_FILE="$STATE_DIR/pocket-id/encryption_key"
  if [ ! -f "$ENCRYPTION_KEY_FILE" ]; then
    openssl rand -base64 32 > "$ENCRYPTION_KEY_FILE"
    chmod 600 "$ENCRYPTION_KEY_FILE"
  fi

  if [ ! -f "$HELLO_FILE" ]; then
    cat > "$HELLO_FILE" <<'EOF'
e2e test report payload
EOF
  fi

  local tailscale_ip hostname_short domain
  tailscale_ip="$(tailscale ip -4)"
  hostname_short="$(scutil --get LocalHostName 2>/dev/null || hostname -s)"
  domain="${hostname_short}.internal"
  POCKET_ID_VHOST="${WORKTREE_ID}-pocket-id-test.${domain}"
  REPORTS_VHOST="${WORKTREE_ID}-reports-test.${domain}"

  export POCKET_ID_APP_URL="https://${POCKET_ID_VHOST}:${CADDY_POCKET_ID_PORT}"
  export POCKET_ID_URL="$POCKET_ID_APP_URL"
  export REPORTS_URL="https://${REPORTS_VHOST}:${CADDY_REPORTS_PORT}"
  export POCKET_ID_DATA_DIR="$STATE_DIR/pocket-id/data"
  export POCKET_ID_KEY_FILE="$ENCRYPTION_KEY_FILE"
  export POCKET_ID_VOLUME_NAME="${PROJECT_NAME}-pocket-id-data"
  export REPORTS_DATA_DIR="$STATE_DIR/reports"

  TAILSCALE_IP="$tailscale_ip"
  DOMAIN="$domain"

  write_env_file
}

check_ports_available() {
  for p in "$POCKET_ID_HOST_PORT" "$CADDY_POCKET_ID_PORT" "$CADDY_REPORTS_PORT" "$OAUTH2_PROXY_PORT"; do
    if ! port_is_free "$p" && [ -z "$(compose ps -a -q 2>/dev/null)" ] && [ ! -f "$CADDY_PID_FILE" ] && [ ! -f "$OAUTH2_PROXY_PID_FILE" ]; then
      die "port $p (persisted for this worktree) is in use by something else. Free it, or delete $ENV_FILE to re-pick ports (this invalidates the registered OIDC client — bootstrap will need to redo the client-creation step)."
    fi
  done
}

# Copies (not live-shares) production Caddy's internal CA root cert+key so
# the test Caddy's tls-internal-issued leaf certs chain to a root already
# trusted by every client that already trusts production's CA — including
# the native oauth2-proxy process (Go reads the macOS System keychain).
ensure_test_ca() {
  mkdir -p "$TEST_CA_DIR"
  if [ ! -f "$TEST_CA_DIR/root.crt" ]; then
    log "copying production's internal CA identity (needs sudo to read /var/lib/caddy)..."
    sudo cp "$PROD_CA_DIR/root.crt" "$PROD_CA_DIR/root.key" "$TEST_CA_DIR/"
    sudo chown "$(id -u):$(id -g)" "$TEST_CA_DIR/root.crt" "$TEST_CA_DIR/root.key"
  fi
}

start_caddy() {
  stop_caddy
  ensure_test_ca

  cat > "$CADDYFILE" <<EOF
{
  admin off
  auto_https disable_redirects
}

https://${POCKET_ID_VHOST}:${CADDY_POCKET_ID_PORT} {
  bind ${TAILSCALE_IP} 127.0.0.1
  tls internal
  reverse_proxy 127.0.0.1:${POCKET_ID_HOST_PORT}
}

# Replicates the production reports vhost from
# modules/static-reports/options.nix: /oauth2/* goes straight to
# oauth2-proxy, everything else is forward_auth'd before file_server.
https://${REPORTS_VHOST}:${CADDY_REPORTS_PORT} {
  bind ${TAILSCALE_IP} 127.0.0.1
  tls internal

  handle /oauth2/* {
    reverse_proxy 127.0.0.1:${OAUTH2_PROXY_PORT} {
      header_up X-Real-IP {remote_host}
      header_up X-Forwarded-Uri {uri}
    }
  }

  handle {
    forward_auth 127.0.0.1:${OAUTH2_PROXY_PORT} {
      uri /oauth2/auth
      header_up X-Real-IP {remote_host}
      @error status 401
      handle_response @error {
        redir * /oauth2/sign_in?rd={scheme}://{host}{uri}
      }
    }

    root * ${REPORTS_DATA_DIR}
    file_server browse
  }
}
EOF

  (
    export CADDY_DATA_DIR XDG_DATA_HOME HOME
    XDG_DATA_HOME="$CADDY_DATA_DIR"
    HOME="$CADDY_DATA_DIR"
    exec nohup nix develop "$REPO_ROOT#e2e" -c caddy run \
      --config "$CADDYFILE" --adapter caddyfile > "$CADDY_LOG_FILE" 2>&1
  ) &
  echo $! > "$CADDY_PID_FILE"

  sleep 1
  if ! kill -0 "$(cat "$CADDY_PID_FILE")" 2>/dev/null; then
    die "test Caddy failed to start — see $CADDY_LOG_FILE"
  fi
  log "pocket-id reachable at: ${POCKET_ID_APP_URL}"
  log "reports gate reachable at: ${REPORTS_URL}"
}

stop_caddy() {
  if [ -f "$CADDY_PID_FILE" ]; then
    kill "$(cat "$CADDY_PID_FILE")" 2>/dev/null || true
    rm -f "$CADDY_PID_FILE"
  fi
}

# oauth2-proxy runs inside the repo's pinned e2e devShell (added to
# flake.nix's devShells.e2e), on a loopback-only port only Caddy reaches.
# It must be started after bootstrap_if_needed: it needs the confidential
# client secret that bootstrap generates and persists into .env.
start_oauth2_proxy() {
  stop_oauth2_proxy
  [ -n "${REPORTS_OIDC_CLIENT_SECRET:-}" ] || die "start_oauth2_proxy: missing REPORTS_OIDC_CLIENT_SECRET (run bootstrap first)"
  [ -n "${REPORTS_OIDC_CLIENT_ID:-}" ] || die "start_oauth2_proxy: missing REPORTS_OIDC_CLIENT_ID"

  # This Pocket ID deployment has no SMTP configured, so every account's
  # emailVerified is permanently false; oauth2-proxy would otherwise
  # reject every login with "email in id_token isn't verified" (see
  # modules/static-reports/options.nix, commit 23aa8ec).
  (
    exec nohup nix develop "$REPO_ROOT#e2e" -c oauth2-proxy \
      --provider=oidc \
      --oidc-issuer-url="${POCKET_ID_APP_URL}" \
      --client-id="${REPORTS_OIDC_CLIENT_ID}" \
      --client-secret="${REPORTS_OIDC_CLIENT_SECRET}" \
      --redirect-url="${REPORTS_URL}/oauth2/callback" \
      --http-address="127.0.0.1:${OAUTH2_PROXY_PORT}" \
      --upstream=static://202 \
      --email-domain='*' \
      --insecure-oidc-allow-unverified-email=true \
      --set-xauthrequest=true \
      --pass-authorization-header=true \
      --reverse-proxy=true \
      --cookie-secret="${REPORTS_COOKIE_SECRET}" \
      --cookie-secure=true \
      --cookie-csrf-per-request=false \
      --skip-provider-button=true \
      --provider-display-name="Pocket ID (e2e)" \
      > "$OAUTH2_PROXY_LOG_FILE" 2>&1
  ) &
  echo $! > "$OAUTH2_PROXY_PID_FILE"

  sleep 3
  if ! kill -0 "$(cat "$OAUTH2_PROXY_PID_FILE")" 2>/dev/null; then
    die "oauth2-proxy failed to start — see $OAUTH2_PROXY_LOG_FILE"
  fi
  log "oauth2-proxy listening on 127.0.0.1:${OAUTH2_PROXY_PORT}"
}

stop_oauth2_proxy() {
  if [ -f "$OAUTH2_PROXY_PID_FILE" ]; then
    kill "$(cat "$OAUTH2_PROXY_PID_FILE")" 2>/dev/null || true
    rm -f "$OAUTH2_PROXY_PID_FILE"
  fi
}

wait_healthy() {
  local name="$1" url="$2"
  log "waiting for $name at $url ..."
  for _ in $(seq 1 60); do
    # -f treats the gate's 302-to-sign-in as success (only >=400 fails),
    # so this doubles as "the forward_auth gate is answering".
    if curl -skf "$url" -o /dev/null 2>/dev/null; then
      log "$name is up"
      return 0
    fi
    sleep 2
  done
  die "$name did not become healthy at $url in time"
}

pocket_id_api() {
  local method="$1" path="$2" body="${3:-}"
  local args=(-sfk -X "$method" "${POCKET_ID_APP_URL}${path}" \
    -H "X-API-KEY: $POCKET_ID_API_KEY" -H "Content-Type: application/json")
  if [ -n "$body" ]; then args+=(-d "$body"); fi
  curl "${args[@]}"
}

bootstrap_if_needed() {
  if [ -n "${POCKET_ID_API_KEY:-}" ] && [ -n "${REPORTS_GROUP_ID:-}" ] && \
     [ -n "${REPORTS_OIDC_CLIENT_ID:-}" ] && [ -n "${REPORTS_OIDC_CLIENT_SECRET:-}" ]; then
    log "already bootstrapped for this worktree, skipping manual setup"
    return 0
  fi

  echo "" >&2
  echo "=== One-time Pocket ID bootstrap for worktree '$WORKTREE_ID' ===" >&2
  echo "1. Open in a browser (locally, or from any other tailnet device):" >&2
  echo "   ${POCKET_ID_APP_URL}/setup" >&2
  echo "   Create the admin account and register a passkey (real Touch ID" >&2
  echo "   / security key required — this cannot be automated)." >&2
  echo "2. Go to Settings -> Admin -> API Keys, create a key, copy it." >&2
  echo -n "Paste the API key here: " >&2
  read -r POCKET_ID_API_KEY
  [ -n "$POCKET_ID_API_KEY" ] || die "no API key entered"
  export POCKET_ID_API_KEY
  write_env_file

  if [ -z "${REPORTS_GROUP_ID:-}" ]; then
    log "creating reports_users group..."
    REPORTS_GROUP_ID=$(pocket_id_api POST /api/user-groups \
      '{"name":"reports_users","friendlyName":"Reports Users"}' | jq -r '.id')
    export REPORTS_GROUP_ID
    write_env_file
  fi

  if [ -z "${REPORTS_OIDC_CLIENT_ID:-}" ] || [ -z "${REPORTS_OIDC_CLIENT_SECRET:-}" ]; then
    log "creating Reports OIDC client (confidential)..."
    if [ -z "${REPORTS_OIDC_CLIENT_ID:-}" ]; then
      REPORTS_OIDC_CLIENT_ID="reports-e2e"
      export REPORTS_OIDC_CLIENT_ID
    fi
    callback_urls=$(jq -n --arg url "$REPORTS_URL" \
      '[$url + "/oauth2/callback"]')
    if ! pocket_id_api GET "/api/oidc/clients/${REPORTS_OIDC_CLIENT_ID}" >/dev/null 2>&1; then
      pocket_id_api POST /api/oidc/clients \
        "$(jq -n --arg id "$REPORTS_OIDC_CLIENT_ID" --argjson cb "$callback_urls" '{
          id: $id,
          name: "Reports (e2e)",
          isPublic: false,
          pkceEnabled: false,
          isGroupRestricted: false,
          callbackURLs: $cb,
          logoutCallbackURLs: $cb
        }')" >/dev/null
    fi
    REPORTS_OIDC_CLIENT_SECRET=$(pocket_id_api POST "/api/oidc/clients/${REPORTS_OIDC_CLIENT_ID}/secret" | jq -r '.secret')
    export REPORTS_OIDC_CLIENT_SECRET
    write_env_file
  fi

  log "bootstrap complete for worktree '$WORKTREE_ID'"
}

cmd_up() {
  derive_env
  check_ports_available
  compose up -d
  start_caddy
  wait_healthy "pocket-id" "${POCKET_ID_APP_URL}/healthz"
  bootstrap_if_needed
  start_oauth2_proxy
  # The gate answering with a redirect is how we know the whole chain
  # (Caddy -> oauth2-proxy -> Pocket ID) is live.
  wait_healthy "reports gate" "${REPORTS_URL}"
  log "stack up. URLs: POCKET_ID_URL=${POCKET_ID_APP_URL} REPORTS_URL=${REPORTS_URL}"
}

cmd_down() {
  derive_env
  stop_oauth2_proxy
  stop_caddy
  compose stop
}

cmd_teardown() {
  derive_env
  stop_oauth2_proxy
  stop_caddy
  compose down -v --remove-orphans 2>/dev/null || true
}

case "${1:-}" in
  up) cmd_up ;;
  down) cmd_down ;;
  teardown) cmd_teardown ;;
  *)
    die "usage: $0 {up|down|teardown}"
    ;;
esac