#!/usr/bin/env bash
# Lifecycle manager for the isolated, per-worktree Navidrome E2E test stack.
# See tests/e2e-navidrome/design.md for the full rationale (why isolated,
# why it never touches the real modules/navidrome instance or its data).
#
# Usage:
#   stack.sh up        Start (creating fresh test data on first run for this worktree)
#   stack.sh down       Stop the containers, keep data
#   stack.sh teardown  Stop the containers AND drop their volumes/data
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
E2E_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$E2E_DIR/../.." && pwd)"

WORKTREE_ID="$(basename "$REPO_ROOT")"
PROJECT_NAME="navidrome-e2e-test-${WORKTREE_ID}"

STATE_DIR="$E2E_DIR/.state"
ENV_FILE="$E2E_DIR/.env"

NAVIDROME_COMPOSE="$REPO_ROOT/modules/navidrome/compose.yaml"
OVERRIDE_COMPOSE="$E2E_DIR/fixtures/navidrome.override.yaml"

log() { echo "[navidrome-e2e-stack] $*" >&2; }
die() {
  echo "[navidrome-e2e-stack] ERROR: $*" >&2
  exit 1
}

find_free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1]); s.close()'
}

compose() {
  docker compose -p "$PROJECT_NAME" \
    -f "$NAVIDROME_COMPOSE" \
    -f "$OVERRIDE_COMPOSE" \
    --env-file "$ENV_FILE" \
    "$@"
}

load_env_file() {
  if [ -f "$ENV_FILE" ]; then
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
  fi
}

write_env_file() {
  cat >"$ENV_FILE" <<EOF
# Generated by tests/e2e-navidrome/scripts/stack.sh — do not commit (gitignored).
# Isolated, disposable data for this worktree's e2e stack only; never
# production. See tests/e2e-navidrome/design.md.
NAVIDROME_TEST_PORT=${NAVIDROME_TEST_PORT}
NAVIDROME_TEST_DATA_DIR=${NAVIDROME_TEST_DATA_DIR}
NAVIDROME_TEST_MUSIC_DIR=${NAVIDROME_TEST_MUSIC_DIR}
NAVIDROME_TEST_URL=${NAVIDROME_TEST_URL}
EOF
}

derive_env() {
  load_env_file
  : "${NAVIDROME_TEST_PORT:=$(find_free_port)}"
  NAVIDROME_TEST_DATA_DIR="$STATE_DIR/data"
  NAVIDROME_TEST_MUSIC_DIR="$STATE_DIR/music"
  NAVIDROME_TEST_URL="http://127.0.0.1:${NAVIDROME_TEST_PORT}"
  # Export both TEST and non-TEST names so the base compose.yaml resolves
  NAVIDROME_PORT="$NAVIDROME_TEST_PORT"
  NAVIDROME_DATA_DIR="$NAVIDROME_TEST_DATA_DIR"
  NAVIDROME_MUSIC_DIR="$NAVIDROME_TEST_MUSIC_DIR"
  export NAVIDROME_TEST_PORT NAVIDROME_TEST_DATA_DIR NAVIDROME_TEST_MUSIC_DIR NAVIDROME_TEST_URL
  export NAVIDROME_PORT NAVIDROME_DATA_DIR NAVIDROME_MUSIC_DIR
  write_env_file
  mkdir -p "$NAVIDROME_TEST_DATA_DIR" "$NAVIDROME_TEST_MUSIC_DIR"
}

wait_healthy() {
  log "waiting for navidrome at ${NAVIDROME_TEST_URL} ..."
  for _ in $(seq 1 60); do
    if curl -sf "${NAVIDROME_TEST_URL}/health" -o /dev/null 2>/dev/null; then
      log "navidrome is up"
      return 0
    fi
    sleep 2
  done
  die "navidrome did not become healthy at ${NAVIDROME_TEST_URL} in time"
}

cmd_up() {
  derive_env
  compose up -d
  wait_healthy
  log "web: ${NAVIDROME_TEST_URL}  data dir: ${NAVIDROME_TEST_DATA_DIR}  music dir: ${NAVIDROME_TEST_MUSIC_DIR}"
}

cmd_down() {
  derive_env
  compose stop
}

cmd_teardown() {
  derive_env
  compose down -v --remove-orphans 2>/dev/null || true
  rm -rf "$NAVIDROME_TEST_DATA_DIR" "$NAVIDROME_TEST_MUSIC_DIR"
}

case "${1:-}" in
up) cmd_up ;;
down) cmd_down ;;
teardown) cmd_teardown ;;
*)
  die "usage: $0 {up|down|teardown}"
  ;;
esac
