#!/usr/bin/env bash
# Lifecycle manager for the isolated, per-worktree Forgejo E2E test stack.
# See tests/e2e-forgejo/design.md for the full rationale (why isolated,
# why it never touches the real modules/forgejo instance or its data).
#
# Usage:
#   stack.sh up        Start (creating fresh test data on first run for this worktree)
#   stack.sh down       Stop the container, keep data
#   stack.sh teardown  Stop the container AND drop its volume/data
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
E2E_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$E2E_DIR/../.." && pwd)"

WORKTREE_ID="$(basename "$REPO_ROOT")"
PROJECT_NAME="forgejo-e2e-test-${WORKTREE_ID}"

STATE_DIR="$E2E_DIR/.state"
ENV_FILE="$E2E_DIR/.env"

FORGEJO_COMPOSE="$REPO_ROOT/modules/forgejo/compose.yaml"
OVERRIDE_COMPOSE="$E2E_DIR/fixtures/forgejo.override.yaml"

log() { echo "[forgejo-e2e-stack] $*" >&2; }
die() {
  echo "[forgejo-e2e-stack] ERROR: $*" >&2
  exit 1
}

find_free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1]); s.close()'
}

compose() {
  docker compose -p "$PROJECT_NAME" \
    -f "$FORGEJO_COMPOSE" \
    -f "$OVERRIDE_COMPOSE" \
    --env-file "$ENV_FILE" \
    "$@"
}

load_env_file() {
  if [ -f "$ENV_FILE" ]; then
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
  fi
}

write_env_file() {
  cat >"$ENV_FILE" <<EOF
# Generated by tests/e2e-forgejo/scripts/stack.sh — do not commit (gitignored).
# Isolated, disposable data for this worktree's e2e stack only; never
# production. See tests/e2e-forgejo/design.md.
FORGEJO_TEST_PROJECT_NAME=${PROJECT_NAME}
FORGEJO_TEST_WEB_PORT=${FORGEJO_TEST_WEB_PORT}
FORGEJO_TEST_SSH_PORT=${FORGEJO_TEST_SSH_PORT}
FORGEJO_TEST_VOLUME_NAME=${FORGEJO_TEST_VOLUME_NAME}
FORGEJO_DATA_DIR=${FORGEJO_DATA_DIR}
FORGEJO_EXTERNAL_URL=${FORGEJO_EXTERNAL_URL}
FORGEJO_OIDC_CLIENT_ID=unused-in-e2e-stack
FORGEJO_OIDC_CLIENT_SECRET=unused-in-e2e-stack
FORGEJO_OIDC_DISCOVERY_URL=http://127.0.0.1:${FORGEJO_TEST_WEB_PORT}/.well-known/openid-configuration
EOF
}

derive_env() {
  load_env_file
  : "${FORGEJO_TEST_WEB_PORT:=$(find_free_port)}"
  : "${FORGEJO_TEST_SSH_PORT:=$(find_free_port)}"
  FORGEJO_TEST_VOLUME_NAME="${PROJECT_NAME}-gitea-data"
  FORGEJO_DATA_DIR="$STATE_DIR/data"
  FORGEJO_EXTERNAL_URL="http://127.0.0.1:${FORGEJO_TEST_WEB_PORT}"
  export FORGEJO_TEST_WEB_PORT FORGEJO_TEST_SSH_PORT FORGEJO_TEST_VOLUME_NAME
  export FORGEJO_DATA_DIR FORGEJO_EXTERNAL_URL
  export FORGEJO_OIDC_CLIENT_ID="unused-in-e2e-stack"
  export FORGEJO_OIDC_CLIENT_SECRET="unused-in-e2e-stack"
  export FORGEJO_OIDC_DISCOVERY_URL="http://127.0.0.1:${FORGEJO_TEST_WEB_PORT}/.well-known/openid-configuration"
  write_env_file
  mkdir -p "$FORGEJO_DATA_DIR"
}

wait_healthy() {
  log "waiting for forgejo at ${FORGEJO_EXTERNAL_URL} ..."
  for _ in $(seq 1 60); do
    if curl -sf "${FORGEJO_EXTERNAL_URL}/api/healthz" -o /dev/null 2>/dev/null; then
      log "forgejo is up"
      return 0
    fi
    sleep 2
  done
  die "forgejo did not become healthy at ${FORGEJO_EXTERNAL_URL} in time"
}

cmd_up() {
  derive_env
  compose up -d
  wait_healthy
  log "web: ${FORGEJO_EXTERNAL_URL}  ssh port: ${FORGEJO_TEST_SSH_PORT}  volume: ${FORGEJO_TEST_VOLUME_NAME}"
}

cmd_down() {
  derive_env
  compose stop
}

cmd_teardown() {
  derive_env
  compose down -v --remove-orphans 2>/dev/null || true
  rm -rf "$FORGEJO_DATA_DIR"
}

case "${1:-}" in
up) cmd_up ;;
down) cmd_down ;;
teardown) cmd_teardown ;;
*)
  die "usage: $0 {up|down|teardown}"
  ;;
esac
